- hosts: localhost
  connection: local
  vars:
    username: benji
    official_packages:
      - docker
      - docker-compose
      - dotnet-runtime
      - dotnet-sdk
      - gcc
      - gnome-system-monitor
      - keepass
      - keepass-plugin-keeagent
      - make
      - nodejs
      - npm
      - pacaur
      - python
      - tmux
      - tree
      - visual-studio-code-bin
      - yarn
      - zsh
    aur_packages:
      - google-chrome
      - dropbox
      - gnome-shell-extension-system-monitor-git
      - tmux-bash-completion
      - circleci-cli
      - kubernetes-bin
      - kubernetes-helm

    yarn:
      - "@angular/cli"
      - "@vue/cli"

    tree:
      - source/perso
      - source/utils
      - source/work

    vscode_extensions:
      - maptz.camelcasenavigation
      - ms-vsliveshare.vsliveshare
      - vscoss.vscode-ansible
      - ms-vscode.csharp
      - esbenp.prettier-vscode

  tasks:
    - name: Install Packages
      pacman:
        name: "{{ official_packages }}"
        state: present
      become: yes
    - name: Install AUR Packages
      with_items: "{{ aur_packages }}"
      aur:
        name: "{{ item }}"
        state: present
    - name: Install yarn global packages
      shell: yarn global add "{{ item }}"
      with_items: "{{ yarn }}"
    - name: Create dotfile symlinks
      file:
        src: "{{ item.src }}"
        dest: ~/.{{ item.path }}
        state: link
        force: yes
      with_filetree: config/
    - name: Create file structure
      file:
        path: "~/{{ item }}"
        state: directory
      with_items: "{{ tree }}"
    - name: Install VS Code Extensions
      shell: code --install-extension "{{ item }}"
      with_items: "{{ vscode_extensions }}"
      register: vscode_result
      changed_when: "'already installed' not in vscode_result.stdout"

    - name: Create Docker groups
      become: yes
      group:
        name: docker
        state: present
      tags:
        - docker

    # it is required to log out and log back in for this step to be effective.
    - name: Add Docker to sudoers
      become: yes
      user:
        append: yes
        groups: docker
        name: "{{ username }}"
      tags:
        - docker

    - name: Enable docker daemon
      service: name=docker state=started enabled=yes
      tags:
        - docker

# TODO
# vs code config
# custom theme
# ansible vault for credentials