- hosts: localhost
  connection: local
  vars:
    username: benji
    official_packages:
      - docker
      - docker-compose
      - dotnet-runtime
      - dotnet-sdk
      - gcc
      - gnome-system-monitor
      - httpie
      - jq
      - keepass
      - keepass-plugin-keeagent
      - make
      - nodejs
      - npm
      - pacaur
      - python
      - python-pip
      - tmux
      - tree
      - visual-studio-code-bin
      - xclip
      - yarn
      - zsh
    aur_packages:
      - aws-cli
      - calibre
      - circleci-cli
      - dropbox
      - google-chrome
      - gnome-shell-extension-system-monitor-git
      - kubernetes-bin
      - kubernetes-helm
      - ngrok
      - signal
      - slack-desktop
      - tmux-bash-completion
      
    yarn:
      - "@angular/cli"
      - "@vue/cli"
      - commitizen
      - conventional-changelog
      - create-react-app
      - static      

    tree:
      - source/perso
      - source/utils
      - source/work

    vscode_extensions:
      - brunnerh.insert-unicode
      - cmstead.jsrefactor
      - dbaeumer.vscode-eslint
      - dsznajder.es7-react-js-snippets
      - eamodio.gitlens
      - eg2.tslint
      - esbenp.prettier-vscode
      - fabiospampinato.vscode-todo-plus
      - flowtype.flow-for-vscode
      - formulahendry.auto-rename-tag
      - joshpeng.sublime-babel-vscode
      - KnisterPeter.vscode-commitizen
      - letrieu.expand-region
      - maptz.camelcasenavigation
      - ms-vscode.csharp
      - ms-vsliveshare.vsliveshare
      - msjsdiag.debugger-for-chrome
      - tomoki1207.vscode-gfm-preview
      - vscoss.vscode-ansible
      - wix.vscode-import-cost

  tasks:
    - name: Install Packages
      pacman:
        name: "{{ official_packages }}"
        state: present
      become: yes
    - name: Install AUR Packages
      with_items: "{{ aur_packages }}"
      aur:
        name: "{{ item }}"
        state: present
    - name: Install yarn global packages
      shell: yarn global add "{{ item }}"
      with_items: "{{ yarn }}"
      become: yes
    - name: Create dotfile symlinks
      file:
        src: "{{ item.src }}"
        dest: ~/.{{ item.path }}
        state: link
        force: yes
      with_filetree: dotfiles/
    - name: Create file structure
      file:
        path: "~/{{ item }}"
        state: directory
      with_items: "{{ tree }}"
    - name: Install VS Code Extensions
      shell: code --install-extension "{{ item }}"
      with_items: "{{ vscode_extensions }}"
      register: vscode_result
      changed_when: "'already installed' not in vscode_result.stdout"

    - name: Create Docker groups
      become: yes
      group:
        name: docker
        state: present
      tags:
        - docker

    # it is required to log out and log back in for this step to be effective.
    - name: Add Docker to sudoers
      become: yes
      user:
        append: yes
        groups: docker
        name: "{{ username }}"
      tags:
        - docker

    - name: Enable docker daemon
      service: name=docker state=started enabled=yes
      tags:
        - docker

# TODO
# vs code config
# custom theme
# ansible vault for credentials

# subliminal
# vlc
# mpv
# https://github.com/vayan/autosub-mpv
# pip : http-prompt
# i3 !!
