- hosts: localhost
  connection: local
  vars:
    username: benji
    official_packages:
      - docker
      - docker-compose
      - gcc
      - httpie
      - jq
      - keepass
      - keepass-plugin-keeagent
      - make
      - nodejs
      - npm
      - pacaur
      - python
      - python-pip
      - tree
      - visual-studio-code-bin
      - xclip
      - yarn
      - zsh
    aur_packages:
      - arc-gtk-theme
      - aws-cli
      - calibre
      - circleci-cli
      - compton
      - dmenu
      - dropbox
      - feh
      - google-chrome
      - i3lock-fancy-git
      - maim
      - otf-font-awesome
      - kubernetes-bin
      - kubernetes-helm
      - ngrok
      - rofi
      - scrot
      - slack-desktop
      - xautolock
      - xorg.xbacklight
      
    yarn:
      - create-react-app
      - static      

    tree:
      - source/perso
      - source/utils
      - source/work

    vscode_extensions:
      - atlassian.atlascode
      - brunnerh.insert-unicode
      - cmstead.jsrefactor
      - codezombiech.gitignore
      - dbaeumer.vscode-eslint
      - dsznajder.es7-react-js-snippets
      - eamodio.gitlens
      - esbenp.prettier-vscode
      - fabiospampinato.vscode-todo-plus
      - formulahendry.auto-rename-tag
      - gamunu.vscode-yarn
      - hbenl.vscode-test-explorer
      - ipedrazas.kubernetes-snippets
      - joshpeng.sublime-babel-vscode
      - kumar-harsh.graphql-for-vscode
      - legfrey.javascript-test-runner
      - maptz.camelcasenavigation
      - mikestead.dotenv
      - ms-kubernetes-tools.vscode-kubernetes-tools
      - ms-vscode.vscode-typescript-tslint-plugin
      - ms-vsliveshare.vsliveshare
      - ms-vsliveshare.vsliveshare-audio
      - Orta.vscode-jest
      - Prisma.vscode-graphql
      - rafaelmaiolla.remote-vscode
      - redhat.vscode-yaml
      - rtbenfield.vscode-jest-test-adapter
      - VisualStudioExptTeam.vscodeintellicode
      - wix.vscode-import-cost

  tasks:
    - name: Install Packages
      pacman:
        name: "{{ official_packages }}"
        state: present
      become: yes
    - name: Install AUR Packages
      with_items: "{{ aur_packages }}"
      aur:
        name: "{{ item }}"
        state: present
    - name: Install yarn global packages
      shell: yarn global add "{{ item }}"
      with_items: "{{ yarn }}"
      become: yes
    - name: Create dotfile symlinks
      file:
        src: "{{ item.src }}"
        dest: ~/.{{ item.path }}
        state: link
        force: yes
      with_filetree: dotfiles/
    - name: Create file structure
      file:
        path: "~/{{ item }}"
        state: directory
      with_items: "{{ tree }}"
    - name: Install VS Code Extensions
      shell: code --install-extension "{{ item }}"
      with_items: "{{ vscode_extensions }}"
      register: vscode_result
      changed_when: "'already installed' not in vscode_result.stdout"

    - name: Create Docker groups
      become: yes
      group:
        name: docker
        state: present
      tags:
        - docker

    # it is required to log out and log back in for this step to be effective.
    - name: Add Docker to sudoers
      become: yes
      user:
        append: yes
        groups: docker
        name: "{{ username }}"
      tags:
        - docker

    - name: Enable docker daemon
      service: name=docker state=started enabled=yes
      tags:
        - docker
    - name: Install services
      with_filetree: services/
      template: 
        src: "{{ item.src }}" 
        dest: "/etc/systemd/system/{{ item.path }}.service"
      become: yes
      tags:
        - services
    - name: Start services
      with_filetree: services/
      systemd: 
        state: started 
        name: "{{ item.path }}"
        daemon_reload: yes
      when: item.path != 'i3lock' # would lock screen
      become: yes
      tags:
       - services
        
# TODO
# vs code config
# custom theme
# ansible vault for credentials

# subliminal
# vlc
# mpv
# https://github.com/vayan/autosub-mpv
# pip : http-prompt
# i3 !!
# pass
