---
- hosts: localhost  
  connection: local
  vars:
    official_packages:
      - docker
      - docker-compose
      - dotnet-runtime
      - dotnet-sdk
      - gcc
      - gnome-system-monitor
      - keepass
      - keepass-plugin-keeagent
      - make
      - nodejs
      - npm
      - pacaur
      - python
      - tree
      - visual-studio-code-bin
      - yarn
      - zsh
    unofficial_packages:
      - dropbox
      - gnome-shell-extension-system-monitor-git
    
    yarn:
      - '@angular/cli'
      - '@vue/cli'

    tree:
      - source/perso
      - source/utils
      - source/work

    vscode_extensions:
      - maptz.camelcasenavigation
      - ms-vsliveshare.vsliveshare
      - vscoss.vscode-ansible
      - ms-vscode.csharp
      
  tasks:
    - name: Install Packages
      pacman: 
        name: "{{ official_packages }}"
        state: present
      become: yes
    - name: Install Unofficial Packages
      with_items: "{{ unofficial_packages }}"
      aur: 
        name: "{{ item }}"
        state: present
    - name: Install yarn global packages
      shell: yarn global add "{{ item }}"
      with_items: "{{ yarn }}"
    - name: Create dotfile symlinks
      file:
        src: '{{ item.src }}'
        dest: ~/.{{ item.path }}
        state: link
        force: yes
      with_filetree: config/
    - name: Create file structure
      file: 
        path: "~/{{ item }}"
        state: directory
      with_items: "{{ tree }}"
    - name: Install VS Code Extensions
      shell: code --install-extension "{{ item }}"
      with_items: "{{ vscode_extensions }}"
      register: vscode_result
      changed_when: "'already installed' not in vscode_result.stdout"
